
1. What are the names of all the countries in the country table?
SELECT COUNTRY_NAME 
FROM COUNTRY;

2. What is the total number of customers in the customers table?
SELECT COUNT(CUSTOMER_ID) AS Total_Customers
FROM CUSTOMERS;

3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
SELECT AVG(AGE) AS Average_Age
FROM CUSTOMERS 
WHERE CAN_EMAIL = "YES";

4. How many orders were made by customers aged 30 or older?
SELECT COUNT(O.ORDER_ID) AS Orders
FROM ORDERS AS O
JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.AGE >= 30;

5. What is the total revenue generated by each product category?
SELECT CATEGORY,
       SUM(PRICE) AS Total_Revenue
FROM PRODUCTS
GROUP BY CATEGORY;

6. What is the average price of products in the 'food' category?
SELECT AVG(PRICE) AS Average_Price
FROM PRODUCTS
WHERE CATEGORY = "FOOD";

7. How many orders were made in each sales channel (sales_channel column) in the orders table?
SELECT SALES_CHANNEL,
       COUNT(ORDER_ID) AS No_of_Orders
FROM ORDERS
GROUP BY SALES_CHANNEL;

8.What is the date of the latest order made by a customer who can receive marketing emails?
SELECT O.DATE_SHOP
FROM ORDERS AS O
JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.CAN_EMAIL = "YES";

9. What is the name of the country with the highest number of orders?
SELECT C.COUNTRY_NAME
FROM COUNTRY AS C
JOIN ORDERS AS O
ON O.COUNTRY_ID = C.COUNTRY_ID
WHERE COUNT(O.ORDER_ID) > 0
GROUP BY C.COUNTRY_NAME
;


10. What is the average age of customers who made orders in the 'vitamins' product category?
SELECT ROUND(AVG(C.AGE)) AS Average_Age
FROM ORDERS AS O
JOIN BASKETS AS B
ON B.ORDER_ID = O.ORDER_ID
JOIN PRODUCTS AS P
ON P.PRODUCT_ID = B.PRODUCT_ID
JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE P.CATEGORY = "VITAMINS"
;

